---
# Download and install EPEL for Centos/RHEL version 8
- name: Download EPEL Repo - Centos/RHEL 8
  get_url: url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install EPEL Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/epel-release-latest-7.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: install python3
  yum: name=python3
